(function () {
  var C = window.CampOps;
  window.CampOpsViews.users = function () {
    return "<div class=\"topbar\"><div><h2>Users</h2><p class=\"muted\">Switch user for this prototype.</p></div></div><section class=\"panel\"><div class=\"grid cols-3\">" + C.state.users.map(function (user) { return "<button class=\"user-switch\" data-user=\"" + user.id + "\"><strong>" + C.esc(user.name) + "</strong><span>" + C.esc(user.role) + " - " + C.esc(user.team) + "</span><small>" + C.esc(user.email || "No email yet") + "</small></button>"; }).join("") + "</div></section>";
  };
  window.CampOpsViews.settings = function () { return "<div class=\"topbar\"><div><h2>Settings</h2><p class=\"muted\">Supabase connection is stored in this browser only.</p></div></div><section class=\"panel\">" + window.CampOpsViews.setupForm(true) + "</section>"; };
  window.CampOpsViews.setupForm = function (showReset) { return "<div class=\"form-grid\" style=\"margin-top:16px\"><div class=\"field full\"><label>Supabase URL</label><input id=\"supabase-url\" placeholder=\"https://your-project.supabase.co\" value=\"" + C.esc(C.config.url || "") + "\"></div><div class=\"field full\"><label>Supabase anon key</label><input id=\"supabase-key\" placeholder=\"ey...\" value=\"" + C.esc(C.config.anonKey || "") + "\"></div><button class=\"btn\" id=\"save-config\">Save connection</button>" + (showReset ? "<button class=\"btn secondary\" id=\"reset-local\">Reset local demo data</button>" : "") + "</div><p class=\"muted\">Run <strong>supabase-schema.sql</strong> in Supabase first. Passwords are not stored by this prototype.</p>"; };
  window.CampOpsViews.setup = function () { return "<div class=\"login-wrap\"><section class=\"login-card\"><div class=\"brand\"><div class=\"brand-mark\">CO</div><div><h1>Camp Ops Setup</h1><p class=\"muted\">Paste your Supabase project URL and anon key to start using the app.</p></div></div>" + window.CampOpsViews.setupForm(false) + "</section></div>"; };
})();
